llm_config:
  model: "gemini/gemini-pro"
host_config:
  host: "0.0.0.0"
  port: 8000
cache_options:
  with_cache: True
  cache_folder: "./Cache"
sources:
  - google_drive_folder:
    kind: gdrive
    config:
      object_id: "1s1tP4CIl-WbVlmps60gyVRq_Y7lTaOs-" 
      service_user_credentials_file: "credentials.json"
      refresh_interval: 5

